name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: openSUSE
    steps:
    - uses: actions/checkout@v2
    - name: Autoconf
      run: autoreconf --install
    - name: configure
      run: ./configure --enable-linuxgpio --disable-parport
    - name: make
      run: make
#    - name: make check
#      run: make check
# Automake also generates a distcheck rule that can be of help to ensure that a given
# distribution will actually work. Simplifying a bit, we can say this rule first makes
# a distribution, and then, operating from it, takes the following steps:
#
# - tries to do a VPATH build (see VPATH Builds), with the srcdir and all its content
#   made read-only;
# - runs the test suite (with make check) on this fresh build;
# - installs the package in a temporary directory (with make install), and runs the
#   test suite on the resulting installation (with make installcheck);
# - checks that the package can be correctly uninstalled (by make uninstall) and
#   cleaned (by make distclean);
# - finally, makes another tarball to ensure the distribution is self-contained. 
#
# All of these actions are performed in a temporary directory.
# Please note that the exact location and the exact structure of such a directory
# (where the read-only sources are placed, how the temporary build and install
# directories are named and how deeply they are nested, etc.) is to be considered
# an implementation detail, which can change at any time; so do not rely on it. 
    - name: make distcheck
      run: make distcheck
